name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:

  sonarqube-dotnet:
    name: SonarQube .NET Analysis
    runs-on: macos-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'
      - name: Install SonarScanner tool
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Run SonarScanner analysis for .NET
        run: |
          dotnet sonarscanner begin /k:"ruivieira03_sem5pi-csharp-only" /o:"ruivieira03" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build MDR/sem5pi-24-25-g034.sln
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
